-- 1. Crear la Base de Datos
CREATE DATABASE IF NOT EXISTS incidenciasMolvizar;
USE incidenciasMolvizar;

-- 2. Tabla de Lugares (Para la lista de la P1 y el script de comentarios)
CREATE TABLE lugares (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_lugar VARCHAR(100) NOT NULL
);

-- 3. Tabla de Noticias
CREATE TABLE noticias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    fecha DATE NOT NULL,
    tipo VARCHAR(50),
    concejalia VARCHAR(100),
    personas TEXT,
    descripcion TEXT,
    id_lugar INT,
    FOREIGN KEY (id_lugar) REFERENCES lugares(id) ON DELETE SET NULL
);

-- 4. Tabla de Imágenes (Relación 1 a N)
CREATE TABLE imagenes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_noticia INT NOT NULL,
    ruta_archivo VARCHAR(255) NOT NULL,
    descripcion_alt VARCHAR(255),
    es_portada BOOLEAN NOT NULL,
    FOREIGN KEY (id_noticia) REFERENCES noticias(id) ON DELETE CASCADE
);

-- 5. Tabla de Comentarios
CREATE TABLE comentarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_noticia INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    texto TEXT NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_noticia) REFERENCES noticias(id) ON DELETE CASCADE
);

-- 1. Insertar Lugares de Molvízar
INSERT INTO lugares (nombre_lugar) VALUES 
('Lobres'), 
('Motril'), 
('Ítrabo'), 
('Almuñecar'),
('Salobreña'),
('Torre Nueva'),
('Vélez de Benaudalla'),
('Calahonda'),
('Molvizar');

-- 2. Insertar Noticias
-- Incluimos los campos requeridos: título, fecha, tipo, concejalía, personas, lugar y descripción
INSERT INTO noticias (titulo, fecha, tipo, concejalia, personas, descripcion, id_lugar) VALUES 
('Mantenimiento en la Iglesia de Santa Ana', '2026-04-20', 'Obra', 'Cultura', 'Operarios municipales', 'Se están realizando labores de limpieza y restauración en la fachada principal para conservar el patrimonio local. Este proyecto de restauración ha sido largamente esperado por los vecinos, quienes consideran la Iglesia de Santa Ana como uno de los monumentos más emblemáticos y de mayor valor histórico de nuestro municipio. Las obras incluyen la limpieza profunda de la piedra original, eliminando décadas de suciedad acumulada por la contaminación y el paso del tiempo. Además, se están llevando a cabo trabajos de consolidación estructural en el campanario, donde se habían detectado pequeñas fisuras que ponían en riesgo la estabilidad a largo plazo. Los operarios municipales, bajo la supervisión de expertos en conservación del patrimonio cultural de la región, están empleando técnicas tradicionales y materiales compatibles con los originales para garantizar que la intervención sea respetuosa y duradera. Se espera que esta primera fase de las obras concluya antes del inicio de las fiestas de verano, permitiendo que tanto residentes como visitantes puedan admirar la iglesia en todo su esplendor. El Ayuntamiento ha destacado que la inversión para este proyecto proviene tanto de fondos municipales como de una subvención especial. Esta intervención no solo persigue embellecer el aspecto estético del edificio, sino también preservar un bien de interés cultural que ha sido testigo de la historia de nuestra localidad durante siglos. A lo largo de las próximas semanas, los andamios cubrirán por completo la entrada principal, lo que ha obligado a reubicar temporalmente los oficios religiosos a la parroquia vecina. Los historiadores locales han aprovechado la ocasión para documentar elementos arquitectónicos que permanecían ocultos bajo el deterioro. Durante el proceso de limpieza, han salido a la luz interesantes grabados en la piedra que datan de la construcción original del templo, un hallazgo arqueológico que ha despertado el interés de la comunidad académica y que será exhibido en futuras exposiciones del museo local. Se ha habilitado también un centro de información en la plaza adyacente donde los vecinos pueden consultar los planos y conocer de cerca los detalles técnicos de esta meticulosa labor de restauración. El equipo técnico confía en que las inclemencias meteorológicas no retrasen el cronograma establecido, permitiendo así disfrutar de este renovado tesoro arquitectónico en la fecha prevista.', 2),
('Gran éxito en las fiestas patronales', '2026-04-22', 'Evento', 'Festejos', 'Vecinos y visitantes', 'La Plaza de la Constitución acogió a cientos de personas durante el pregón de este año. Las festividades comenzaron con un vibrante desfile de cabezudos y charangas que recorrieron las calles principales, llenando el ambiente de música, color y alegría. Este año, el comité organizador se superó a sí mismo ofreciendo un programa repleto de actividades para todas las edades, desde talleres infantiles y juegos tradicionales por la mañana, hasta conciertos de bandas locales y verbenas populares que se prolongaron hasta altas horas de la madrugada. El punto culminante de la jornada inaugural fue, sin duda, el emotivo pregón pronunciado por uno de los ciudadanos más ilustres del municipio, cuyas palabras resonaron profundamente entre los asistentes, recordando anécdotas del pasado y haciendo un llamado a la unidad y celebración comunitaria. La asistencia masiva ha supuesto también un importante impulso económico para los comercios y la hostelería local, que han reportado un incremento significativo en sus ventas. Las fuerzas de seguridad confirmaron que la jornada transcurrió sin incidentes destacables, demostrando el civismo del evento. Durante la semana grande, se celebraron además certámenes gastronómicos donde los restaurantes de la zona compitieron por ofrecer la mejor tapa tradicional, atrayendo a paladares exigentes y fomentando la riqueza culinaria de la región. Los más pequeños pudieron disfrutar de castillos hinchables, cuentacuentos y una multitudinaria fiesta de la espuma que sirvió para combatir las altas temperaturas de estos días festivos. Por otro lado, la feria de día instalada en el recinto ferial se convirtió en el punto de encuentro por excelencia de grupos de amigos y familias enteras, compartiendo risas y bailes bajo las carpas engalanadas. Se organizaron competiciones deportivas de carácter amistoso que fomentaron la deportividad y el compañerismo entre los participantes. La clausura de las fiestas se cerró con un espectacular castillo de fuegos artificiales que iluminó el cielo nocturno, dejando una imagen imborrable en la memoria de los presentes. El balance final realizado por las autoridades ha sido extraordinariamente positivo, superando el récord de asistencia de la edición anterior y consolidando estas fiestas como un referente ineludible en el calendario cultural y de ocio de toda la comarca.', 1),
('Aviso de corte de agua por avería', '2026-04-25', 'Urgente', 'Servicios', 'Técnicos de mantenimiento', 'Debido a una rotura en la Calle Real, el suministro permanecerá cortado hasta media tarde. La avería se produjo de madrugada, cuando una de las tuberías principales de distribución sufrió una fractura imprevista, provocando una fuga considerable que afectó rápidamente a los bloques adyacentes. Desde primera hora de la mañana, un equipo especializado de operarios y técnicos de mantenimiento de la empresa suministradora se ha desplazado al lugar para evaluar los daños y proceder con las reparaciones pertinentes. Los trabajos de excavación ya han comenzado para acceder a la sección dañada de la infraestructura, la cual, según las primeras estimaciones, requerirá la sustitución de un tramo de varios metros debido a su antigüedad y desgaste estructural. Las autoridades locales han emitido un comunicado urgente solicitando a los vecinos de las zonas afectadas que extremen las medidas de ahorro de agua y paciencia, garantizando que se está trabajando a contrarreloj para restablecer el servicio a la mayor brevedad posible. Se han dispuesto camiones cisterna en varios puntos estratégicos. A medida que avanzaban las horas, los servicios técnicos identificaron que la rotura era más compleja de lo estimado inicialmente, ya que las raíces de unos árboles centenarios cercanos habían comprometido seriamente la canalización subterránea. Esta situación ha obligado a movilizar maquinaria pesada adicional para despejar la zona sin causar daños colaterales a la flora protegida del entorno ni a los cimientos de los edificios colindantes. Protección Civil ha establecido un perímetro de seguridad para garantizar que los transeúntes no sufran ningún percance durante las labores de arreglo. En paralelo, los servicios sociales del ayuntamiento están realizando llamadas de seguimiento a personas mayores y dependientes que residen en el área sin suministro, para asegurar que cuentan con agua embotellada y la asistencia necesaria durante estas horas críticas. Para mitigar los inconvenientes, se han repartido circulares informativas y se mantiene un hilo de actualización constante a través de las redes sociales oficiales del municipio. Se estima que, una vez instalados los nuevos conductos de polietileno de alta resistencia, se procederá a un purgado progresivo de la red antes de reanudar el flujo habitual.', 3),
('Nueva ruta de senderismo inaugurada', '2026-04-26', 'Deporte', 'Turismo', 'Senderistas', 'Se ha inaugurado una nueva ruta de senderismo que recorre los paisajes más emblemáticos de la zona, atrayendo a numerosos aficionados a la naturaleza. Este nuevo itinerario, bautizado como Sendero de los Miradores, ofrece a los caminantes un trayecto de dificultad moderada que se extiende a lo largo de doce kilómetros a través de bosques autóctonos, valles frondosos y crestas montañosas. El proyecto ha sido diseñado pensando en la preservación del entorno natural, utilizando materiales sostenibles para la señalización y habilitando pasarelas de madera en las zonas más sensibles para evitar la erosión del suelo. A lo largo del recorrido, se han instalado varios paneles informativos que detallan la flora y fauna locales, así como la historia geológica de la región, convirtiendo la caminata en una experiencia tanto deportiva como educativa. Durante el acto de inauguración, que contó con la presencia de autoridades locales y representantes de clubes de montaña, se organizó una primera marcha oficial que superó todas las expectativas de asistencia. Esta iniciativa busca promover un turismo activo y ecológico en la zona. El trazado de la ruta ha sido meticulosamente planeado para incluir paradas en puntos de avistamiento de aves, donde los senderistas pueden observar especies endémicas que anidan en los acantilados rocosos colindantes. Se han establecido también pequeñas áreas de descanso equipadas con mesas de picnic fabricadas con madera reciclada y contenedores de separación de residuos para promover la conciencia medioambiental. Las asociaciones de comerciantes locales han expresado su satisfacción, anticipando que el flujo constante de caminantes beneficiará directamente a los restaurantes y alojamientos rurales de las proximidades. Además, se planea lanzar una aplicación móvil gratuita que guíe a los usuarios a lo largo del sendero, ofreciendo datos de interés mediante realidad aumentada e integrando funcionalidades de emergencia geolocalizada para aumentar la seguridad. Los promotores ya estudian la posibilidad de conectar este nuevo tramo con rutas de largo recorrido que cruzan otras comarcas, lo que situaría al municipio en el mapa del senderismo nacional y europeo como un destino de referencia ineludible.', 9),
('Taller de agricultura ecológica para jóvenes', '2026-04-27', 'Educación', 'Medio Ambiente', 'Estudiantes locales', 'Gran éxito de participación en el primer taller de agricultura ecológica enfocado a los jóvenes del municipio, promoviendo el cuidado del medio ambiente. A lo largo de la semana, decenas de estudiantes locales se han reunido en los huertos comunitarios para aprender de primera mano las técnicas de cultivo sostenible, prescindiendo del uso de pesticidas y fertilizantes químicos. El programa del taller ha abarcado desde la preparación del suelo y la creación de compost orgánico, hasta los métodos naturales para el control de plagas y la recolección de semillas. Impartido por ingenieros agrónomos y agricultores experimentados de la zona, el curso ha combinado sesiones teóricas con un fuerte componente práctico, permitiendo a los jóvenes ensuciarse las manos y conectar directamente con la tierra. La iniciativa ha sido aplaudida por padres y educadores, quienes ven en esta actividad una forma excelente de inculcar valores de respeto hacia la naturaleza, responsabilidad y trabajo en equipo. Los productos cultivados serán donados al banco de alimentos local. El entusiasmo de los participantes ha desbordado las expectativas iniciales, lo que ha llevado a ampliar los horarios de apertura de los huertos para que los jóvenes puedan continuar atendiendo sus plantaciones en sus horas libres. En las parcelas de prueba se han sembrado variedades hortícolas tradicionales que se creían perdidas, fomentando así la biodiversidad y el rescate de la memoria agrícola de la región. El programa ha incluido también un módulo especial sobre la recolección eficiente y almacenamiento del agua de lluvia, introduciendo sistemas de riego por goteo artesanales que optimizan este recurso tan valioso. Varias escuelas del municipio ya han mostrado interés en incorporar este modelo a su currículo educativo para el próximo curso escolar. La culminación de esta actividad formativa se celebrará con un mercado solidario al aire libre, donde los propios alumnos podrán ofrecer sus cosechas ecológicas a los vecinos, demostrando que la soberanía alimentaria y el respeto al medio ambiente son pilares fundamentales para el futuro desarrollo de nuestra sociedad comunitaria.', 9),
('Renovación del polideportivo municipal', '2026-04-28', 'Obra', 'Deportes', 'Trabajadores de la construcción', 'Las obras de mejora y ampliación del polideportivo municipal han dado comienzo esta semana, con el objetivo de ofrecer mejores instalaciones a los deportistas. Este ambicioso proyecto de remodelación integral responde a las históricas demandas de los clubes locales y usuarios particulares, quienes llevaban años solicitando una modernización de las infraestructuras. La primera fase de los trabajos se centrará en la renovación completa del pavimento de las pistas interiores, sustituyendo el antiguo material por una superficie de última generación que minimiza el riesgo de lesiones y mejora el rendimiento deportivo. Posteriormente, se procederá a la instalación de un nuevo sistema de iluminación LED de alta eficiencia energética, que no solo garantizará una visibilidad óptima para las competiciones nocturnas, sino que también supondrá un ahorro significativo en la factura eléctrica del consistorio. Además, el proyecto contempla la ampliación de la zona de vestuarios, adaptándolos a las normativas vigentes de accesibilidad universal, y la creación de una nueva sala polivalente destinada a actividades dirigidas. El recinto exterior también se beneficiará de importantes mejoras, incluyendo la construcción de dos nuevas pistas de pádel acristaladas y la rehabilitación del campo de fútbol de césped artificial. Todo el complejo contará con un innovador sistema de aislamiento térmico para mejorar la climatización durante todo el año, reduciendo la huella de carbono de la instalación. Los aficionados a los deportes de raqueta han acogido con gran alegría la noticia, ya que llevaban años organizando recogidas de firmas para aumentar las infraestructuras dedicadas a estas modalidades. Asimismo, se habilitará una nueva zona de aparcamiento disuasorio con plazas reservadas para vehículos eléctricos y puntos de recarga gratuitos. Desde la concejalía de deportes se ha asegurado que estas obras no interrumpirán completamente la actividad deportiva de los más jóvenes, y que se publicarán calendarios alternativos de entrenamientos. La fecha prevista para la gran reinauguración coincidirá con la gala anual del deporte local, donde se espera la presencia de figuras relevantes del panorama nacional.', 9),
('Exposición de fotografía antigua', '2026-04-29', 'Evento', 'Cultura', 'Fotógrafos e historiadores', 'La Casa de la Cultura acoge una exposición única con fotografías históricas que muestran la evolución de nuestra localidad durante el último siglo. Bajo el título Memoria en Blanco y Negro, esta muestra recopila más de un centenar de imágenes inéditas que han sido cuidadosamente restauradas por expertos archivistas y cedidas por diversas familias del municipio. A través de este recorrido visual, los visitantes pueden observar la drástica transformación de nuestras calles, plazas y edificios más representativos, así como la evolución de las costumbres, oficios tradicionales y celebraciones festivas a lo largo de las décadas. La exposición está estructurada cronológicamente y temáticamente, dedicando secciones especiales a los antiguos oficios agrícolas, los primeros medios de transporte y los eventos sociales que marcaron época. Como actividad complementaria, se han organizado visitas guiadas para los centros educativos, donde historiadores locales explican a las nuevas generaciones el contexto y la importancia histórica de cada fotografía. La muestra permanecerá abierta de forma gratuita. Los organizadores han dispuesto pantallas interactivas donde los visitantes pueden hacer zoom sobre los detalles más minuciosos de las instantáneas y comparar el mismo encuadre con una fotografía tomada en la actualidad, creando un fascinante diálogo entre el pasado y el presente. A lo largo del mes, se celebrarán también mesas redondas y charlas impartidas por profesores de historia y antropología que analizarán el impacto de la revolución industrial en la demografía local. El archivo municipal ha habilitado un pequeño puesto de digitalización donde cualquier vecino puede llevar sus álbumes familiares para ser escaneados e incorporados al patrimonio documental público, garantizando así que estas joyas visuales no se pierdan con el tiempo. El éxito de la convocatoria ha propiciado la creación de un catálogo impreso de alta calidad que estará a la venta en la biblioteca, cuyos beneficios irán íntegramente destinados a futuras labores de restauración documental en beneficio de nuestra rica herencia colectiva.', 5),
('Campaña de adopción de mascotas', '2026-04-30', 'Social', 'Bienestar Animal', 'Voluntarios y protectoras', 'La nueva campaña de adopción busca encontrar un hogar para los animales rescatados durante los últimos meses, con una gran respuesta por parte de los vecinos. Organizada en colaboración con diversas protectoras de la provincia, esta iniciativa tiene como lema No compres de raza, adopta uno sin casa, y pretende concienciar sobre el grave problema del abandono animal, especialmente crítico en los meses previos al verano. El evento central de la campaña tuvo lugar este fin de semana en el parque municipal, donde se habilitaron zonas de juego y socialización para que las familias interesadas pudieran interactuar con los perros y gatos en adopción en un ambiente relajado y seguro. Además de facilitar las adopciones directas, la jornada incluyó charlas informativas sobre tenencia responsable, cuidados veterinarios básicos y la importancia de la esterilización para controlar la superpoblación felina y canina. El balance del primer fin de semana ha sido calificado de extraordinario, habiéndose formalizado más de una veintena de adopciones exitosas. El programa ha introducido este año una novedosa iniciativa de apadrinamiento dirigida a aquellas personas que, por sus circunstancias de vida, no pueden adoptar definitivamente pero desean contribuir económicamente a la manutención y cuidados veterinarios de un animal específico. Se organizaron también demostraciones de obediencia básica y agilidad canina que sirvieron para demostrar el enorme potencial y la capacidad de aprendizaje de los perros mestizos rescatados de las calles. Diversos comercios locales han donado sacos de pienso premium, correas y camas, que se sortearon en una rifa solidaria cuya recaudación será destinada a la construcción de un nuevo refugio municipal. Los veterinarios voluntarios realizaron chequeos gratuitos y pusieron microchips a precios muy reducidos para animar a la regularización de las mascotas. La ola de empatía generada por este evento ha dejado claro que nuestra sociedad está cada vez más comprometida con el bienestar de aquellos seres vulnerables que dependen enteramente de nuestro cariño, respeto y protección.', 4);

-- 3. Insertar Imágenes
-- Noticia 1: Galería completa (> 4 imágenes) para cumplir el punto 8 de la práctica
INSERT INTO imagenes (id_noticia, ruta_archivo, descripcion_alt, es_portada) VALUES 
(1, 'imgs/articulos/iglesia_frontal.jpg', 'Vista frontal de la Iglesia de Santa Ana', TRUE),
(1, 'imgs/articulos/iglesia_detalle.jpg', 'Detalle de la piedra restaurada', FALSE);

-- Imágenes para el resto de noticias
INSERT INTO imagenes (id_noticia, ruta_archivo, descripcion_alt, es_portada) VALUES 
(2, 'imgs/articulos/fiesta_pregon.jpg', 'Momento del pregón en la plaza', TRUE),
(3, 'imgs/articulos/averia_calle.jpg', 'Maquinaria reparando la tubería', TRUE),
(4, 'imgs/articulos/ruta_senderismo.png', 'Senderistas caminando por la nueva ruta', TRUE),
(5, 'imgs/articulos/agricultura_ecologica.png', 'Jóvenes plantando hortalizas en el taller', TRUE),
(6, 'imgs/articulos/obras_polideportivo.png', 'Estado de las obras del polideportivo', TRUE),
(7, 'imgs/articulos/exposicion_fotografia.png', 'Visitantes observando las fotografías antiguas', TRUE),
(8, 'imgs/articulos/adopcion_mascotas.png', 'Voluntario con un perro en adopción', TRUE);

-- 4. Insertar Comentarios
INSERT INTO comentarios (id_noticia, nombre, email, texto) VALUES 
(1, 'María López', 'mlopez@correo.es', '¡Qué bien que cuiden nuestra Iglesia de Santa Ana! Hacía falta.'),
(2, 'Pedro G.', 'pedrito@molvizar.com', 'Hacía años que no veía la Plaza de la Constitución tan llena.'),
(3, 'Vecino Indignado', 'vecino@gmail.com', 'Esperemos que arreglen pronto lo de la Calle Real, que es la vía principal.');